name: nasa_daily_snapshot
description: A Flutter application that displays NASA's Astronomy Picture of the Day.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.1.0
  intl: ^0.18.0
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  provider: ^6.1.2
  share_plus: ^7.2.1
  gal: ^2.3.0
  permission_handler: ^11.0.1
  flutter_local_notifications: ^17.0.0
  dio: ^5.3.2
  path_provider: ^2.1.1
  device_info_plus: ^9.1.0
  firebase_core: any
  firebase_auth: any
  google_sign_in: any
  cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
