// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfoQnt64nzKb2fxh0b4fM8Va6rxhPgjZ4',
    appId: '1:1051259865595:web:49a0ddbed5c2a4f590a35e',
    messagingSenderId: '1051259865595',
    projectId: 'nasasnapshots',
    authDomain: 'nasasnapshots.firebaseapp.com',
    storageBucket: 'nasasnapshots.firebasestorage.app',
    measurementId: 'G-GKCJNMY7JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBAXT2h4viHmqyq_djBxQ8HsxlTQ5goQw',
    appId: '1:1051259865595:android:fb61508c0794bdf390a35e',
    messagingSenderId: '1051259865595',
    projectId: 'nasasnapshots',
    storageBucket: 'nasasnapshots.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMctU9Pvo2Syn0pePJuWVgJnZuf9Kwz_s',
    appId: '1:1051259865595:ios:f563d84517ada45490a35e',
    messagingSenderId: '1051259865595',
    projectId: 'nasasnapshots',
    storageBucket: 'nasasnapshots.firebasestorage.app',
    iosBundleId: 'com.example.nasaDailySnapshot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMctU9Pvo2Syn0pePJuWVgJnZuf9Kwz_s',
    appId: '1:1051259865595:ios:f563d84517ada45490a35e',
    messagingSenderId: '1051259865595',
    projectId: 'nasasnapshots',
    storageBucket: 'nasasnapshots.firebasestorage.app',
    iosBundleId: 'com.example.nasaDailySnapshot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfoQnt64nzKb2fxh0b4fM8Va6rxhPgjZ4',
    appId: '1:1051259865595:web:3b57ae9e638ba85c90a35e',
    messagingSenderId: '1051259865595',
    projectId: 'nasasnapshots',
    authDomain: 'nasasnapshots.firebaseapp.com',
    storageBucket: 'nasasnapshots.firebasestorage.app',
    measurementId: 'G-RRTJ4R5S2T',
  );
}
